/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.UnsupportedLookAndFeelException;

public class vistaRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form vistaAdmin
     */
    public vistaRecepcionista() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        controladorVistaRecepcionista ConSidebar = new controladorVistaRecepcionista (this);
        alumnos adm = new  alumnos();
        controladorvistas.removeAll();
        controladorvistas.add(adm).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        alumno = new javax.swing.JButton();
        controladorvistas = new javax.swing.JPanel();
        libros = new javax.swing.JButton();
        tablet = new javax.swing.JButton();
        prestamos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alumno.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/alumnos.png"))); // NOI18N
        alumno.setText("Alumnos");
        alumno.setIconTextGap(10);
        jPanel1.add(alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 250, 70));

        javax.swing.GroupLayout controladorvistasLayout = new javax.swing.GroupLayout(controladorvistas);
        controladorvistas.setLayout(controladorvistasLayout);
        controladorvistasLayout.setHorizontalGroup(
            controladorvistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );
        controladorvistasLayout.setVerticalGroup(
            controladorvistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        jPanel1.add(controladorvistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1230, 630));

        libros.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        libros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libros.png"))); // NOI18N
        libros.setText("Libros");
        libros.setIconTextGap(10);
        jPanel1.add(libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 250, 70));

        tablet.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        tablet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tablet.png"))); // NOI18N
        tablet.setText("Tablets");
        tablet.setIconTextGap(10);
        jPanel1.add(tablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 10, 250, 70));

        prestamos.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        prestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prestamo.png"))); // NOI18N
        prestamos.setText("Prestamos");
        prestamos.setIconTextGap(10);
        jPanel1.add(prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1004, 10, 250, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaRecepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton alumno;
    public javax.swing.JPanel controladorvistas;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton libros;
    public javax.swing.JButton prestamos;
    public javax.swing.JButton tablet;
    // End of variables declaration//GEN-END:variables
}
